# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposdeservicio',
            name='imagen',
        ),
        migrations.AddField(
            model_name='comentario',
            name='correo',
            field=models.CharField(default='test@test.co', max_length=1000),
            preserve_default=False,
        ),
    ]
